version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: contacts_enrich
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # named volume (persists across runs)
      - ./pg-init:/docker-entrypoint-initdb.d  # (optional: for seed scripts)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    restart: always
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data  #named volume for Metabase application data
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin  #named volume for PGAdmin
    depends_on:
      - postgres

volumes:
  pgdata:
  metabase-data:
  pgadmin-data:
